### ISSUE TITLE
Setup plugin repo

### ISSUE THREAD

**Issue by kenodegard** [anaconda/conda-anaconda-tos#4]
Template initial repo using https://github.com/conda/conda-plugin-template

## Tasks

- [ ] Initialize this repo with cookiecutter template
- [ ] Add `LICENSE` file
- [ ] Add `disclaimer.txt` (enforced with `pre-commit`)
- [ ] Include `pyproject.toml`
- [ ] Include conda recipe (`recipe/meta.yaml`)
